const getEnv = name => process.env[`VUE_APP_${name}`];

export default Object.freeze({
  FIREBASE_APIKEY: getEnv('FIREBASE_APIKEY'),
  FIREBASE_AUTH_DOMAIN: getEnv('FIREBASE_AUTH_DOMAIN'),
  FIREBASE_DATABASE_URL: getEnv('FIREBASE_DATABASE_URL'),
  FIREBASE_PROJECT_ID: getEnv('FIREBASE_PROJECT_ID'),
  FIREBASE_STORAGE_BUCKET: getEnv('FIREBASE_STORAGE_BUCKET'),
  FIREBASE_MESSAGE_SENDER_ID: getEnv('FIREBASE_MESSAGE_SENDER_ID'),
  FIREBASE_APP_ID: getEnv('FIREBASE_APP_ID'),
});
